# Generated by Django 4.1.1 on 2023-06-15 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websiteapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='img',
            field=models.ImageField(default='baby', upload_to='gallery'),
            preserve_default=False,
        ),
    ]
